palace/urls.py
from django.urls import path
from . import views

app_name = "palace"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('games', views.GameIndexView.as_view(), name='games'),
    path('players/<str:player>/', views.PlayerView.as_view(), name='player'),
    path('profile/', views.SelfPlayerView, name='profile'),
    path("lobby/<str:lobby_name>/", views.LobbyView, name="lobby"),
    path("lobby0/", views.LobbyZed, name="lobby0"),
    path("lobbyplayers/<str:lobby_name>", views.LobbyPlayers, name="players")
]

palacesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('palace/', include('palace.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='palace/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('users.urls')),
    #register, login
    path('accounts/', include('django.contrib.auth.urls')),
    #logout
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("register/", views.sign_up, name="register"),
    path("login/", views.sign_in.as_view(), name="login"),
]

palace/models.py
from django.db import models
from django.conf import settings

CHAT_ZONES = (
    ("game", "GAME"),
    ("mafia", "MAFIA"),
    ("private", "PRIVATE"),
)

# The player model
class Player(models.Model):
    # Each player is connected to one of the 'user' Django authentication models
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        related_name="player",
        on_delete=models.CASCADE,
    )

    # This field says which lobby the player is in
    ingame = models.ForeignKey(
        'Game',
        on_delete=models.SET_NULL,
        related_name="players",
        default="",
        blank=True,
        null=True,
    )
    
    player = models.CharField(max_length=16, default="")
    wins = models.IntegerField()

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return self.user.username


# The game model
class Game(models.Model):
    name = models.TextField()
    capacity = models.SmallIntegerField(default=6)

    winners = models.ManyToManyField(Player, related_name="winners")

    # The name that will appear in the address bar
    lobby_name = models.SlugField(unique=True)


class Game_Message(models.Model):
    game = models.ForeignKey(Game, on_delete=models.PROTECT, related_name="messages")

    sender = models.ForeignKey(Player, on_delete=models.PROTECT, related_name="sent")
    chat_zone = models.CharField(max_length=16, choices=CHAT_ZONES, default="data")
    private_recipient = models.ForeignKey(
        Player, on_delete=models.PROTECT, related_name="received", blank=True
    )
    is_vote = models.BooleanField(null=False)
    is_status = models.BooleanField(null=False)

    message = models.TextField(default="")
    timestamp = models.DateTimeField(auto_now_add=True)

palace/views.py
from typing import Any
from django.shortcuts import render
from django.views import generic
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect

from .models import Player, Game


class IndexView(generic.TemplateView):
    template_name = "palace/index.html"

class GameIndexView(generic.TemplateView):
    template_name = "palace/game_index.html"

    def get_context_data(self, **kwargs):
        context = super(GameIndexView, self).get_context_data(**kwargs)
        context['lobbies'] = Game.objects.all()
        return context


@login_required
def SelfPlayerView(request):
    username = request.user.username
    return redirect("../players/" + username)


class PlayerView(generic.DetailView):
    slug_url_kwarg = "player"  # this the `argument` in the URL conf
    slug_field = "player"

    model = Player
    template_name = "palace/profile.html"

@login_required
def LobbyView(request, lobby_name):
    # User enters a lobby. If not in the database already, it is created
    lobby, created = Game.objects.get_or_create(lobby_name=lobby_name)

    # But maybe the user is already in a game... lets check
    # [Checking which specific user made this HTTP request
    # is possible because of the @login_required decorator above]
    if request.user.player.ingame != None and request.user.player.ingame != lobby:
        return HttpResponse("<h1>You're in a game already</h1>")

    elif request.user.player.ingame == None:
        request.user.player.ingame = lobby
        request.user.player.save()

    # Dynamically render an HTML page for them
    return render(
        request,
        "palace/lobby.html",
        {
            # "Context" dictionaries are passed so the page rendered
            # is a specific lobby
            "lobby_name": lobby.lobby_name,
            "players": lobby.players.order_by("player"),
        },
    )

def LobbyZed(request):
    return redirect("../lobby/0")

def LobbyPlayers(request, lobby_name):
    lobby = Game.objects.get(lobby_name=lobby_name)

    return render(
        request,
        "palace/lobbyplayers.html",
        {
            "lobby_name": lobby.lobby_name,
            "players": lobby.players.order_by("player"),
        },
    )

templates/palace/game_index.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<section>
    <h1 class="text-center title">Lobbies</h1>

    <div class="specific-w-300 mw-100 mx-auto card mt-3">
        <ul class="list-group list-group-flush" id="games">
            {% for lobby in lobbies %}
            <li
                class="list-group-item player list-group-item-action d-flex justify-content-between align-items-center py-2">
                <span>
                    <a href="{% url 'palace:lobby' lobby_name=lobby.lobby_name %}">
                        {{ lobby.name }}
                    </a>
                </span>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

{% block script %}

{% endblock %}

templates/palace/index.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<section>
    <h1 class="text-center title">Palace</h1>
    <h4 class="text-center">Palace is a party game of deduction, investigation, and mystery solving.</h1>
        <ul class="rules list-unstyled">
            <li>
                <h6>This is how the games go:</h6>

                <ol>
                    <li>You are dealt a card with your role</li>

                    <li>If you are the <span class="badge text-bg-warning">king</span>, try to not reveal your identity,
                        the beast is out to get you</li>

                    <li>If you are one of the <span class="badge text-bg-info">guards</span>, the king's identity has
                        been revealed to you, try to keep it secret</li>

                    <li>If you are the <span class="badge text-bg-dark">beast</span>, you can attempt to pounce on the
                        king at any time, but then you will be revealed and detained</li>

                    <li>At the end of two minute cycles, all players vote to kick a player out of the palace</li>

                    <li>The palace team wins if they kick the beast out of the palace</li>

                    <li>The beast wins if they have defeated the king</li>
                </ol>
            </li>
        </ul>

</section>
{% endblock %}

{% block script %}

{% endblock %}

templates/palace/lobby.html
{% extends "base_generic.html" %}
{% load static %}

{% block title %}
<title>Palace inGame</title>
{% endblock %}

{% block navbar %} {% endblock %}

{% block content %}
<div class="container ps-md-sbwidth h-100">
    <!---The player list box-->
    <div class="sidebar offcanvas-start offcanvas-md d-flex flex-column justify-content-start pt-4" tabindex="-1">
        <a class="navbar-brand mx-auto mb-5" href="{% url 'palace:index' %}">
            <img src="{% static '/logo.png' %}" alt="Logo" width="24" height="24" class="d-inline-block align-text-top">
            Palace
        </a>
        <div class="specific-w-300 mw-100 mx-auto card">
            <ul class="list-group list-group-flush" id="lobby-items">
                <li class="list-group-item d-flex justify-content-between align-items-center py-2">
                    <span>Players:</span>
                    <span id="capacity">
                        <span id="player-count">{{ players|length }}</span>/6
                    </span>
                </li>

                <li class="list-group-item">
                    <div class="progress" role="progressbar" aria-label="Striped animated example"
                        aria-valuenow="{{ players|length }}" aria-valuemin="0" aria-valuemax="6">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" id="timer"
                            style="width: {% widthratio players|length 1 16.66 %}%;"></div>
                    </div>
                </li>

            </ul>
        </div>

        <div class="specific-w-300 mw-100 mx-auto card mt-3">
            <ul class="list-group list-group-flush" id="lobby-players">
                {% for player in players %}

                <li class="list-group-item player list-group-item-action d-flex justify-content-between align-items-center py-2"
                    id="player-{{player.player}}"><span id="player-name-{{player.player}}">{{ player.player}}</span>
                </li>

                {% endfor %}
            </ul>
        </div>
    </div>

    <!---The chat box-->
    <h1 class="text-center title pt-4">Lobby {{ lobby_name }}</h1>

    <div readonly id="chat-log" class="form-control mx-auto w-100 h-75 mb-3 vstack gap-2 overflow-y-auto">
        <div></div>
    </div>
    <div class="input-group mb-3">
        <input id="chat-message-input" class="form-control w-75" type="text" aria-label="Username"><br>
        <input id="chat-message-submit" class="btn btn-primary" type="button" value="Send">
    </div>
</div>
{{ lobby_name|json_script:"lobby-name" }}
{% endblock %}

{% block script %}
<script>
    const roomName = JSON.parse(document.getElementById('lobby-name').textContent);
    var selfplayer;
    var selfbeast = false;

    /*
    Websocket Code
    */

    //A new WebSocket is made, a continual connection between user and server
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/palace/'
        + roomName
        + '/'
    );

    //The WebSocket received a message from the server
    chatSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);

        //Did a player send a message?
        if (data["type"] === "chat") {
            txt = document.createElement("span");
            txt.textContent = data.username + ': ' + data.message;
            document.querySelector('#chat-log').appendChild(txt);
        }

        //Did the server send a message?
        else if (data["type"] === "broadcast") {
            roomMessage(data["message"], data["theme"]);
        }

        //Did the server say game state has changed?
        else if (data["type"] === "event") {
            //Did a player join?
            if (data["event"] === "users") {
                refreshPlayers();
            }
            //Did the game begin?
            else if (data["event"] === "beginning") {
                roomMessage(data["message"], data["theme"]);
                gameBegin();
            }
            //Did a new cycle start?
            else if (data["event"] === "new_cycle") {
                roomMessage(data["message"], data["theme"]);
                newCycle();
            }
            //Is a role being shared?
            else if (data["event"] === "role") {
                revealRole(data["player"], data["role"]);
            }
            //Put the '(You)' next to player
            else if (data["event"] === "self") {
                selfplayer = data["player"];
                selfBadge(data["player"]);
            }
            //Was a player voted out?
            else if (data["event"] === "out") {
                playerStatusUpdate(data["player"], "out");
            }
            //Did a player disconnect?
            else if (data["event"] === "disconnected") {
                playerStatusUpdate(data["player"], "disconnected");
            }
            //Did a player reconnect?
            else if (data["event"] === "reconnected") {
                playerStatusUpdate(data["player"], "reconnected");
            }
        }
    };

    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) { // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function (e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));
        messageInputDom.value = '';
    };

    /*
    Game Logic (Global)
    */

    function roomMessage(update, theme) {
        let txt = document.createElement("span");
        txt.textContent = update;

        txt.className = "badge rounded-pill text-bg-" + theme + " w-50 mx-auto";

        document.querySelector('#chat-log').appendChild(txt);
    }

    function gameBegin() {
        $("#timer").width("100%");
        $("#timer").animate({ width: "0%" }, 5000, "linear", function () {
            $("#timer").animate({ width: "100%" }, 400, "swing");
        });
    }

    function newCycle() {
        var x = 1;
        $(".player").each(function () {
            console.log(this.id);
            console.log("player-" + selfplayer);
            if (this.id != "player-" + selfplayer) {
                $(this).append('<input type="radio" name="radio-group-vote" value="' + this.id.substring(7) + '" class="btn-check cycle-action game-vote" id="voter-' + x + '" autocomplete="off"> <label class="btn btn-outline-primary cycle-action" for="voter-' + x + '">Vote</label>');
                x++;
            }
        });

        $('.game-vote').change(function () {
            const message = $('input[name=radio-group-vote]:checked').val();
            console.log("voted for " + message);

            chatSocket.send(JSON.stringify({
                'message': "v>" + message
            }));
        })

        if (selfbeast) {
            var x = 1;
            $(".player").each(function () {
                if (this.id != "player-" + selfplayer) {
                    $(this).append('<input type="radio" name="radio-group-jump" value="' + this.id.substring(7) + '" class="btn-check cycle-action" id="jump-' + x + '" autocomplete="off"> <label class="btn btn-outline-primary cycle-action" for="jump-' + x + '">Jump</label>');
                    x++;
                }
            });
        }

        $("#timer").animate({ width: "0%" }, 50000, "swing", function () {
            $("#timer").animate({ width: "100%" }, 400, "swing");
        });

        setTimeout(() => {
            endCycle();
        }, 50000);
    }

    function endCycle() {
        const message = $('input[name=radio-group-vote]:checked').val();
        const messagejump = $('input[name=radio-group-jump]:checked').val();

        if (selfbeast && !!messagejump) {
            chatSocket.send(JSON.stringify({
                'message': "j>" + messagejump
            }));
        }

        chatSocket.send(JSON.stringify({
            'message': "c>" + message
        }));

        $(".cycle-action").each(function () {
            $(this).remove();
        });
    }

    function refreshPlayers() {
        $("#lobby-players").load(location.href + " #lobby-players");
        $("#lobby-items").load(location.href + " #lobby-items");
    }

    function playerStatusUpdate(player, status) {
        var playerDom = $("#player-" + player);
        var lobbyCountDom = $("#player-count")

        if (status === "disconnected") {
            playerDom.append("<span class='badge text-bg-secondary' id='" + player + "-disconnected'>Disconnected</span>");
        }

        if (status === "reconnected") {
            $("#" + player + "-disconnected").remove();
        }

        if (status === "out") {
            playerDom.append("<span class='badge text-bg-danger' id='" + player + "-out'>Out</span>");
        }
    }

    function revealRole(player, role) {
        let name = player;
        let char = role;

        var playerDom = $("#player-" + name);
        txt = document.createElement("span");

        switch (char) {
            case 'King':
                playerDom.append("<span class='badge text-bg-warning'>King</span>");

                if (name === selfplayer) {
                    txt.textContent = 'Your role is King!';
                    txt.className = "badge rounded-pill text-bg-warning w-50 mx-auto";
                }
                break;
            case 'Beast':
                playerDom.append("<span class='badge text-bg-dark'>Beast</span>");

                if (selfplayer === name) {
                    selfbeast = true;
                    txt.textContent = 'Your role is Beast!';
                    txt.className = "badge rounded-pill text-bg-dark w-50 mx-auto";
                }
                break;
            case 'Guard':
                playerDom.append("<span class='badge text-bg-info'>Guard</span>");
                if (player === selfplayer) {
                txt.textContent = 'Your role is Guard!';
                txt.className = "badge rounded-pill text-bg-info w-50 mx-auto";
                }
                break
        }

        document.querySelector('#chat-log').appendChild(txt);
    }

    function selfBadge(player) {
        let name = player;

        var playerDom = $("#player-name-" + name);

        playerDom.append("<span class='badge'>You</span>");
    }

    $(document).ready(function () {
        refreshPlayers()
        //reloading lobbyplayers template

    });

    /*
    Game Logic (Character Specific)
    */

</script>
{% endblock %}

templates/palace/lobbyplayers.html
{% for player in players %}

<li class="list-group-item player list-group-item-action d-flex justify-content-between align-items-center py-2"
    id="player-{{player.player}}"><span id="player-name-{{player.player}}">{{ player.player }}</span></li>

{% endfor %}

templates/palace/profile.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<div class="profile">
    <h3 class="text-center">{{ player.user }}'s Profile</h3>
    <div class="card specific-w-300 mw-100 mx-auto">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{ player.user }}'s wins: {{ player.wins }}</li>
            <li class="list-group-item">List group item 2</li>
            <li class="list-group-item">List group item 3</li>
        </ul>
    </div>
</div>
{% endblock %}