palace/urls.py
from django.urls import path
from . import views

app_name = "palace"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('games', views.GameIndexView.as_view(), name='games'),
    path('players/<str:player>/', views.PlayerView.as_view(), name='player'),
    path('profile/', views.SelfPlayerView, name='profile'),
    path("lobby/<str:lobby_name>/", views.LobbyView, name="lobby"),
    path("lobby0/", views.LobbyZed, name="lobby0"),
    path("lobbyplayers/<str:lobby_name>", views.LobbyPlayers, name="players")
]

palacesite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('palace/', include('palace.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='palace/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('users.urls')),
    #register, login
    path('accounts/', include('django.contrib.auth.urls')),
    #logout
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("register/", views.sign_up, name="register"),
    path("login/", views.sign_in.as_view(), name="login"),
]

templates/base_generic.html
<!DOCTYPE html>
<html lang="en" data-bs-core="modern" data-bs-theme="dark">

<head>
  {% block title %}
  <title>Palace</title>
  {% endblock %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/halfmoon@2.0.1/css/halfmoon.min.css" rel="stylesheet"
    integrity="sha256-SsJizWSIG9JT9Qxbiy8xnYJfjCAkhEQ0hihxRn7jt2M=" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>

<body class="overflow-visible">
  {% block navbar %} {% include "navbar.html" %} {% endblock %}

  {% if not user.is_authenticated %}
  {# modal for sign in #}
  <div class="modal fade" id="signinDia" tabindex="-1" aria-labelledby="modal-title-7" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="modal-title-7">
            Sign in to your account
            <br />
            <small class="text-body-secondary fw-normal">Welcome back!</small>
          </h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div id="modal-form" class="signinDia-body">
          {# login form rendered here at document ready #}
        </div>
      </div>
    </div>
  </div>

  {# modal for registration #}
  <div class="modal fade" id="regiDia" tabindex="-1" aria-labelledby="modal-title-7" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="modal-title-7">
            Sign up for an account
            <br />
            <small class="text-body-secondary fw-normal">Please enter your details below</small>
          </h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="regiDia-body">
          {# registration form rendered here at document ready #}
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  {% block content %}
  <!-- default content text (typically empty) -->
  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>

  {% if not user.is_authenticated %}
  <script>
    //At page load...
    $(document).ready(function () {

      //Find the inner elements of sign in and sign up dialogs
      var signinDia = $(".signinDia-body");
      var regiDia = $(".regiDia-body")

      //Generate the contents of the sign-in <dialog>
      //Django syntax for a URL ...  in the users app
      //What is being "get" requested is not an entire HTML page
      //But just an HTML file with a sign in <form>
      $.get("{% url 'users:login' %}", function (data) {
        //Get response is inserted into the modal sign in dialog
        signinDia.html(data);
      });

      //Generate the contents of the sign-up <dialog>
      $.get("{% url 'users:register' %}", function (data) {
        regiDia.html(data);
      });
    });
  </script>
  {% endif %}
  
  {% block script %}
  {% endblock script %}
</body>

</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg"
    style="background-color: var(--bs-content-bg); border-bottom: var(--bs-border-width) solid var(--bs-content-border-color);">
    <div class="container-md">
        <a class="navbar-brand" href="{% url 'palace:index' %}">
            <img src="{% static '/logo.png' %}" alt="Logo" width="24" height="24" class="d-inline-block align-text-top">
            Palace
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapse-1"
            aria-controls="navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <a type="button" class="btn btn-secondary position-relative ms-2" href="{% url 'palace:lobby0' %}">
                    <span class="material-symbols-outlined fa-light fa-user me-1 buttons">
                        playing_cards
                    </span> <span class="buttons">Play</span>
                    <!--- <span class="badge position-absolute top-0 start-100 translate-middle rounded-pill bg-danger p-1">
                        <span class="visually-hidden">New alerts</span>
                    </span>
                    --->
                </a>
                <a type="button" class="btn btn-secondary position-relative ms-2" href="{% url 'palace:profile' %}">
                    <span class="material-symbols-outlined fa-light fa-user me-1 buttons">
                        account_circle
                    </span> <span class="buttons">Profile</span>
                    <!--- <span class="badge position-absolute top-0 start-100 translate-middle rounded-pill bg-danger p-1">
                        <span class="visually-hidden">New alerts</span>
                    </span>
                    --->
                </a>
                <li class="nav-item">
                    <form method="post" action="{% url 'logout' %}?next={% url 'palace:index' %}">
                        {% csrf_token %}
                        <button type="submit" class="nav-link">Sign Out</button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item">
                    <span id="navBtn" class="nav-link" aria-current="page" data-bs-toggle="modal"
                        data-bs-target="#signinDia">Sign in</span>
                </li>
                <li class="nav-item">
                    <span id="navBtn" class="nav-link" aria-current="page" data-bs-toggle="modal"
                        data-bs-target="#regiDia">Sign up</span>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>